//calculating remaing time
const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
const weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const giveaway=document.querySelector(".giveaway");
const deadline=document.querySelector(".deadline");
const items=document.querySelectorAll(".dealine-format h4");
let temDate=new Date();
let tempYear=temDate.getFullYear();
let tempMonth=temDate.getMonth();
let tempDay=temDate.getDate();
const futureDate=new Date(tempYear,tempMonth,tempDay+10,11,30,0);//year,month,day+10,hour,minutes,second
//let futureDate=new Date(2020,9,24,11,30,0);
const year=futureDate.getFullYear();
const hour=futureDate.getHours();
const min=futureDate.getMinutes();
const date=futureDate.getDate();
let month=futureDate.getMonth();
let day=futureDate.getDay();
giveaway.textContent=`giveaway ends on ${weekdays[day]}  ${date} ${months[month]} ${year} ${hour}:${min}pm `;
const futureTime=futureDate.getTime();
const today=new Date().getTime();
	const t=futureTime-today;
	const oneDay=24*60*60*1000;
	const oneHour=60*60*1000;
	const oneMinute=60*1000;
	let days=t/oneDay;
	days=Math.floor(days);
 let hours=Math.floor((t%oneDay)/oneHour);
 let minutes=Math.floor((t%oneHour)/oneMinute);
 let seconds=Math.floor((t%oneMinute)/1000);
 //human readable time
  let sec=seconds%60;
   let min=parseInt((seconds%3600)/60);
   let hr=parseInt(seconds/3600);